# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oles/sailfish/app-sources/harbour-amazfish

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oles/sailfish/app-sources/harbour-amazfish

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oles/sailfish/app-sources/harbour-amazfish/CMakeFiles /home/oles/sailfish/app-sources/harbour-amazfish//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oles/sailfish/app-sources/harbour-amazfish/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qble

# Build rule for target.
qble: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qble
.PHONY : qble

# fast build rule for target.
qble/fast:
	$(MAKE) $(MAKESILENT) -f qble/CMakeFiles/qble.dir/build.make qble/CMakeFiles/qble.dir/build
.PHONY : qble/fast

#=============================================================================
# Target rules for targets named qble_autogen

# Build rule for target.
qble_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qble_autogen
.PHONY : qble_autogen

# fast build rule for target.
qble_autogen/fast:
	$(MAKE) $(MAKESILENT) -f qble/CMakeFiles/qble_autogen.dir/build.make qble/CMakeFiles/qble_autogen.dir/build
.PHONY : qble_autogen/fast

#=============================================================================
# Target rules for targets named libamazfish

# Build rule for target.
libamazfish: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libamazfish
.PHONY : libamazfish

# fast build rule for target.
libamazfish/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/libamazfish.dir/build.make lib/CMakeFiles/libamazfish.dir/build
.PHONY : libamazfish/fast

#=============================================================================
# Target rules for targets named libamazfish_autogen

# Build rule for target.
libamazfish_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libamazfish_autogen
.PHONY : libamazfish_autogen

# fast build rule for target.
libamazfish_autogen/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/libamazfish_autogen.dir/build.make lib/CMakeFiles/libamazfish_autogen.dir/build
.PHONY : libamazfish_autogen/fast

#=============================================================================
# Target rules for targets named harbour-amazfishd

# Build rule for target.
harbour-amazfishd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 harbour-amazfishd
.PHONY : harbour-amazfishd

# fast build rule for target.
harbour-amazfishd/fast:
	$(MAKE) $(MAKESILENT) -f daemon/CMakeFiles/harbour-amazfishd.dir/build.make daemon/CMakeFiles/harbour-amazfishd.dir/build
.PHONY : harbour-amazfishd/fast

#=============================================================================
# Target rules for targets named daemon_translations

# Build rule for target.
daemon_translations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 daemon_translations
.PHONY : daemon_translations

# fast build rule for target.
daemon_translations/fast:
	$(MAKE) $(MAKESILENT) -f daemon/CMakeFiles/daemon_translations.dir/build.make daemon/CMakeFiles/daemon_translations.dir/build
.PHONY : daemon_translations/fast

#=============================================================================
# Target rules for targets named harbour-amazfishd_autogen

# Build rule for target.
harbour-amazfishd_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 harbour-amazfishd_autogen
.PHONY : harbour-amazfishd_autogen

# fast build rule for target.
harbour-amazfishd_autogen/fast:
	$(MAKE) $(MAKESILENT) -f daemon/CMakeFiles/harbour-amazfishd_autogen.dir/build.make daemon/CMakeFiles/harbour-amazfishd_autogen.dir/build
.PHONY : harbour-amazfishd_autogen/fast

#=============================================================================
# Target rules for targets named libwatchfish

# Build rule for target.
libwatchfish: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libwatchfish
.PHONY : libwatchfish

# fast build rule for target.
libwatchfish/fast:
	$(MAKE) $(MAKESILENT) -f daemon/libwatchfish/CMakeFiles/libwatchfish.dir/build.make daemon/libwatchfish/CMakeFiles/libwatchfish.dir/build
.PHONY : libwatchfish/fast

#=============================================================================
# Target rules for targets named libwatchfish_autogen

# Build rule for target.
libwatchfish_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libwatchfish_autogen
.PHONY : libwatchfish_autogen

# fast build rule for target.
libwatchfish_autogen/fast:
	$(MAKE) $(MAKESILENT) -f daemon/libwatchfish/CMakeFiles/libwatchfish_autogen.dir/build.make daemon/libwatchfish/CMakeFiles/libwatchfish_autogen.dir/build
.PHONY : libwatchfish_autogen/fast

#=============================================================================
# Target rules for targets named QtAES

# Build rule for target.
QtAES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtAES
.PHONY : QtAES

# fast build rule for target.
QtAES/fast:
	$(MAKE) $(MAKESILENT) -f daemon/Qt-AES/CMakeFiles/QtAES.dir/build.make daemon/Qt-AES/CMakeFiles/QtAES.dir/build
.PHONY : QtAES/fast

#=============================================================================
# Target rules for targets named QtAES_autogen

# Build rule for target.
QtAES_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QtAES_autogen
.PHONY : QtAES_autogen

# fast build rule for target.
QtAES_autogen/fast:
	$(MAKE) $(MAKESILENT) -f daemon/Qt-AES/CMakeFiles/QtAES_autogen.dir/build.make daemon/Qt-AES/CMakeFiles/QtAES_autogen.dir/build
.PHONY : QtAES_autogen/fast

#=============================================================================
# Target rules for targets named harbour-amazfish-ui

# Build rule for target.
harbour-amazfish-ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 harbour-amazfish-ui
.PHONY : harbour-amazfish-ui

# fast build rule for target.
harbour-amazfish-ui/fast:
	$(MAKE) $(MAKESILENT) -f ui/CMakeFiles/harbour-amazfish-ui.dir/build.make ui/CMakeFiles/harbour-amazfish-ui.dir/build
.PHONY : harbour-amazfish-ui/fast

#=============================================================================
# Target rules for targets named ui_translations

# Build rule for target.
ui_translations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_translations
.PHONY : ui_translations

# fast build rule for target.
ui_translations/fast:
	$(MAKE) $(MAKESILENT) -f ui/CMakeFiles/ui_translations.dir/build.make ui/CMakeFiles/ui_translations.dir/build
.PHONY : ui_translations/fast

#=============================================================================
# Target rules for targets named harbour-amazfish-ui_autogen

# Build rule for target.
harbour-amazfish-ui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 harbour-amazfish-ui_autogen
.PHONY : harbour-amazfish-ui_autogen

# fast build rule for target.
harbour-amazfish-ui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f ui/CMakeFiles/harbour-amazfish-ui_autogen.dir/build.make ui/CMakeFiles/harbour-amazfish-ui_autogen.dir/build
.PHONY : harbour-amazfish-ui_autogen/fast

#=============================================================================
# Target rules for targets named o2

# Build rule for target.
o2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 o2
.PHONY : o2

# fast build rule for target.
o2/fast:
	$(MAKE) $(MAKESILENT) -f ui/o2/src/CMakeFiles/o2.dir/build.make ui/o2/src/CMakeFiles/o2.dir/build
.PHONY : o2/fast

#=============================================================================
# Target rules for targets named o2_autogen

# Build rule for target.
o2_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 o2_autogen
.PHONY : o2_autogen

# fast build rule for target.
o2_autogen/fast:
	$(MAKE) $(MAKESILENT) -f ui/o2/src/CMakeFiles/o2_autogen.dir/build.make ui/o2/src/CMakeFiles/o2_autogen.dir/build
.PHONY : o2_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... QtAES_autogen"
	@echo "... daemon_translations"
	@echo "... harbour-amazfish-ui_autogen"
	@echo "... harbour-amazfishd_autogen"
	@echo "... libamazfish_autogen"
	@echo "... libwatchfish_autogen"
	@echo "... o2_autogen"
	@echo "... qble_autogen"
	@echo "... ui_translations"
	@echo "... QtAES"
	@echo "... harbour-amazfish-ui"
	@echo "... harbour-amazfishd"
	@echo "... libamazfish"
	@echo "... libwatchfish"
	@echo "... o2"
	@echo "... qble"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

