// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_amazfish.cpp"
#include "UVLADIE3JM/moc_amazfishconfig.cpp"
#include "2JQT26BTCO/moc_city.cpp"
#include "2JQT26BTCO/moc_citymanager.cpp"
#include "2JQT26BTCO/moc_citysearchmodel.cpp"
#include "2JQT26BTCO/moc_currentweather.cpp"
